export SECRETS_NAMESPACE='squince'
export SECRETS_SHARED_NAMESPACE='developmentglobal'
export SECRETS_CREDENTIAL_SOURCE='file'

export SMTP_PORT=1025
export SMTP_HOST=ship.glgresearch.com
export SMTP_SERVER=127.0.0.1
export OVERRIDE_EMAIL_RECIPIENT=squince@glgroup.com
export LOGIN_EMAIL_RECIPIENT=squince@glgroup.com

# NPM GIT SECURITY CRAP
# *********************
export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa'

# used for doing npm builds that require private github repos inside of a docker container
export DOCKER_GITHUB_SSH_PATH=~/.ssh/dockergithub
export GITHUB_SSH_KEY=$(cat $DOCKER_GITHUB_SSH_PATH | base64)

# AWS SECURITY
export AWS_ACCESS_KEY_ID="ASIA4UNGEM3QZBCCUZVS"
export AWS_SECRET_ACCESS_KEY="MsmdqWDMhsiNjf7XY5OOmBMVfVyhjvdEP9XcEZda"
export AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjED4aCXVzLWVhc3QtMSJHMEUCIDe7fO3siM7+7M2GTaMpWgMESjZz748vYphasPllJlRJAiEA9E7MB+SYWCqPkMoGLe7l0eXjv8pjtO5eE2hE69wFJccqkAMIFxAAGgw4Njg0Njg2ODA0MTciDLJzA0ZC2vMpp9YXMCrtAs2YM1BqqJF3Tpmd/MUGYWr10etfuCLlDkCVdEGK+qT3Ly0pqcnfqg1BYCtsO3mWgZUFJNCVWcMIYb68rnX5NXOuRgWG7OuBiSA3s6cFPOVDgQ1/gIvCPDOfkBRotXlWpWw8oexjgblNmp9OYh0IcQnD5LECTE/qeFVi3Wh5QrRxGCemeaP/wN5SfQ4OcYzACDSnD91vakojRi5QSDyZXNbeaeLBQwPKA4bKd5bXvRF449exOKjPaKGm3mYrf86HJc4vpRVFTa8jLxewsnOdPkarZr+c1GB3uCadZoPmMN6JBVMVcNu9ORBvw1a6ldqpuu0UWKm/+NIYBW5s0h7maOoIzQRoH/QrzsSoUtsZ8KNw1NDVG5druxo9vK3FDsR/ebJyP2KTWj1SvObTR/XktN1xpnSX+1XV2ymX8fX11fyhbKC/6aHSnTtJ+Nr8Pk8xstkpixRcFt5i5Z7buosMfm9ZjG7biopj0yuQV2vxMKPO6ZMGOqYBYgpDOLb98X0+38wrEmg8kqZ3TodaM69o3E+y38YmyFbsZ4VP5tWA1FkilLOfn/WMdLVaAzldw+TrFStb+2NtGQWZGsJiL3enCCmXf1Pkrq7Aa8h2SW0ru7U385+Q+sSfe5qK9gsRE188x3Z/DdUti0TTCaPv6TAbJrM1ZDbGlKrstXrvkMaXpTG+60m28yj3iLsTqfWc7o27jks9l4UQVM3fws/kaw=="
